import {HAIR_STYLES,HAIR_COLOURS,SKIN_COLOURS,EYE_STYLES,EYE_COLOURS,OUTFITS,OUTFIT_COLOURS,ACCESSORIES,LOOK_NAMES,type CharacterAppearance} from './CharacterAppearance';
export type WardrobeTab='hair'|'face'|'outfit'|'extras';
export type PreviewPose='idle'|'walk'|'attack';
export function dressingRoom(draft:CharacterAppearance,tab:WardrobeTab,created:boolean,level:number,pose:PreviewPose,thumbnail:(look:CharacterAppearance)=>string):string {
  const tabs:[WardrobeTab,string,string][]=[['hair','Hair','✂'],['face','Face','◉'],['outfit','Outfit','♧'],['extras','Extras','✦']];
  const swatches=(key:keyof CharacterAppearance,colours:readonly string[],name:string)=>`<fieldset class="wardrobe-group"><legend>${name}</legend><div class="swatch-grid">${colours.map((colour,n)=>`<button class="wardrobe-swatch" data-action="appearance:${key}:${colour}" style="--swatch:${colour}" aria-label="${name} ${n+1}" aria-pressed="${draft[key]===colour}" title="${name} ${n+1}"></button>`).join('')}</div></fieldset>`;
  const cards=(key:keyof CharacterAppearance,values:readonly string[],title:string,head=false)=>`<fieldset class="wardrobe-group"><legend>${title}<small>${values.length} unlocked</small></legend><div class="look-grid ${head?'face-grid':'outfit-grid'}">${values.map(value=>`<button class="look-card" data-action="appearance:${key}:${value}" aria-label="${LOOK_NAMES[value]??value}" aria-pressed="${draft[key]===value}"><div class="look-thumb ${head?'head-thumb':'outfit-thumb'}"><img src="${thumbnail({...draft,[key]:value})}" alt="" draggable="false"></div><span>${LOOK_NAMES[value]??value}</span></button>`).join('')}</div></fieldset>`;
  let content='';
  if(tab==='hair')content=cards('hairStyle',HAIR_STYLES,'Choose your hair',true)+swatches('hair',HAIR_COLOURS,'Hair colour');
  if(tab==='face')content=`<fieldset class="wardrobe-group"><legend>Character</legend><div class="body-options">${['male','female'].map(value=>`<button data-action="appearance:sex:${value}" aria-pressed="${draft.sex===value}">${value==='male'?'Male':'Female'}</button>`).join('')}</div></fieldset>`+cards('eyeStyle',EYE_STYLES,'Eye style',true)+swatches('eyes',EYE_COLOURS,'Eye colour')+swatches('skin',SKIN_COLOURS,'Skin tone');
  if(tab==='outfit')content=cards('outfit',OUTFITS,'Pick an outfit')+swatches('outfitColour',OUTFIT_COLOURS,'Outfit colour');
  if(tab==='extras')content=cards('accessory',ACCESSORIES,'Finishing touches',true)+`<p class="wardrobe-note">Mix every outfit and accessory freely. Your look is yours to change.</p>`;
  return `<div class="dressing-layout"><section class="avatar-bay" aria-label="Character preview"><div class="avatar-nameplate"><small>BUILDING 100 · NEW ADVENTURER</small><b>Your student</b><span>LV ${level}</span></div><div class="avatar-sparks" aria-hidden="true"><span>✦</span><span>✧</span><span>·</span><span>✦</span><span>·</span></div><div class="avatar-stage"><img src="${thumbnail(draft)}" alt="Live character preview"></div><div class="avatar-platform" aria-hidden="true"></div><div class="avatar-look-name">${LOOK_NAMES[draft.outfit]}<small>${LOOK_NAMES[draft.hairStyle]} · ${LOOK_NAMES[draft.eyeStyle]}</small></div><div class="avatar-preview-actions"><button data-action="preview-turn" aria-label="Turn character">↔ Turn</button><button data-action="preview-pose:idle" aria-pressed="${pose==='idle'}">Idle</button><button data-action="preview-pose:walk" aria-pressed="${pose==='walk'}">Walk</button><button data-action="preview-pose:attack" aria-pressed="${pose==='attack'}">Attack</button></div><button class="wardrobe-shuffle" data-action="random-character">✧ Random look</button></section><section class="wardrobe-panel" aria-label="Customize character"><div class="wardrobe-heading"><div><h2>Make it yours</h2><p>Pick your look. Find your way up.</p></div><span>ALL STYLES FREE</span></div><div class="preset-row" aria-label="Starter looks"><span>Quick looks</span><button data-action="look-preset:classic">Cloud</button><button data-action="look-preset:meadow">Meadow</button><button data-action="look-preset:midnight">Midnight</button></div><div class="wardrobe-tabs" role="tablist" aria-label="Appearance categories">${tabs.map(([id,name,icon])=>`<button class="wardrobe-tab" role="tab" id="wardrobe-tab-${id}" aria-controls="wardrobe-panel" aria-selected="${tab===id}" data-action="wardrobe-tab:${id}"><span aria-hidden="true">${icon}</span>${name}</button>`).join('')}</div><div class="wardrobe-content" id="wardrobe-panel" role="tabpanel" aria-labelledby="wardrobe-tab-${tab}" tabindex="0">${content}</div><div class="wardrobe-footer"><div class="wardrobe-summary"><b>${LOOK_NAMES[draft.outfit]}</b><span>Change your look any time from Menu.</span></div><button class="wardrobe-confirm primary" data-action="save-character">${created?'Save & play':'Start adventure'} <span aria-hidden="true">▶</span></button></div></section></div>`;
}
